### ISSUE TITLE
dist JS file not up-to-date

### ISSUE THREAD

**Issue by runderworld** [cmstead/DataMother.js#1]
The dist JS file is not up-to-date to reflect the latest source code.

**Comment by cmstead** [comment]
D'oh! I didn't realize that there was an issue and a PR. I just pushed a new version.

**Comment by cmstead** [comment]
All set: https://github.com/cmstead/DataMother.js/releases/tag/1.0.3

**Comment by runderworld** [comment]
:thumbsup:
